name: "Pull Request Review"
on:
  pull_request:
    branches:
      - 'develop'

jobs:
  review:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup swiftlint
        run: |
          brew install swiftlint
      - name: Setup danger
        run: gem install danger danger-swiftlint
      - name: Run danger
        run: danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
