name: "Pull Request Review"
on:
  pull_request:
    branches:
      - 'develop'

jobs:
  review:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup swiftlint
        run: |
          brew unlink swiftlint
          brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/bbf6c86ae53bd2accf8fd00995903b98c140085b/Formula/swiftlint.rb
      - name: Setup danger
        run: gem install danger danger-swiftlint
        env:
          SWIFTLINT_VERSION: 0.39.1
      - name: Run danger
        run: danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
